### PR TITLE
Upgrade to Bevy 0.13

### PR DESCRIPTION
**Pull request by rparrett**
Nothing crazy in here, just a bunch of tedious little changes from LWIM and Bevy.

I am not sure what your workflow is with the `dolly` submodule, so I didn't touch it, but the only changes required in `dolly` seemed to be a Bevy version number bump.

### CODE REVIEW

**Comment by janhohenheim** [comment]
@rparrett thanks for having a migration branch ready for me to use 😉

**Comment by rparrett** [comment]
Assuming CI failures are due to me having totally ignored the `dolly` submodule -- that repo needs a bevy 0.13 branch, which should just be a bevy version number bump.

**Comment by BlackPhlox** [comment]
Hi @rparrett no worries, I have a bit of time today for which I can look into this. Been busy with work up until now, should be an easy bump fix

**Comment by rparrett** [comment]
Thanks!

**Pull request merged**
